info:
  contact: { }
paths:
  /group/exit:
    get:
      consumes:
        - multipart/form-data
      description: room_id token 为必填
      parameters:
        - description: 群号
          in: query
          name: room_id
          required: true
          type: string
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"退出成功！"}'
          schema:
            type: string
      summary: 退出群聊接口
      tags:
        - 公共方法
  /group/group:
    post:
      consumes:
        - multipart/form-data
      description: info token 为必填
      parameters:
        - description: token
          in: header
          name: token
          required: true
          type: string
        - description: 群名称
          in: formData
          name: info
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code": 200,"msg": "创建群聊成功,群号为:8660920"}'
          schema:
            type: string
      summary: 创建群聊接口
      tags:
        - 公共方法
  /group/grouperlist:
    get:
      consumes:
        - multipart/form-data
      description: token 为必填
      parameters:
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: "{\t\"code\": 200,\t\"data\": [ { \"roomidently\": \"3725963\",
            \"useridently\": \"\", \"room_type\": \"group\", \"creaet_time\": 0, \"create_uesr\":
            \"admin\", \"info\": \"小学生\" } ], \"msg\": \"获取数据成功！\" }"
          schema:
            type: string
      summary: 群列表
      tags:
        - 公共方法
  /group/grouplist:
    get:
      consumes:
        - multipart/form-data
      description: room_id  为必填
      parameters:
        - description: 群号
          in: query
          name: room_id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: "{\"code\": 200,\"data\": {\t\"data\": [\t{\t\"Indently\":
            \"6a2a462c-a107-48ea-82e5-74e308327e6f\",\t\"Username\": \"admin\", \"Password\":
            \"21232f297a57a5a743894a0e4a801fc3\",\t\"Use_status\": 0,\t\"Register_time\":
            \"2023-03-13 17:05:08\",\t\"Email\": \"3096407764@qq.com\",\t\"account\":
            \"3169387148\"\t},\t{\t\t\"Indently\": \"cacda2d3-4a77-4afa-94b5-6ff2c036d126\",
            \"Username\": \"leilong\",\t\t   \"Password\": \"e10adc3949ba59abbe56e057f20f883e\",
            \"Use_status\": 0, \"Register_time\": \"2023-03-12 19:07:16\",\"Email\":
            \"3096407768@qq.com\", \"account\": \"9546270155\"}]\t}, \"msg\": \"获取数据成功！\"}"
          schema:
            type: string
      summary: 获取群成员列表接口
      tags:
        - 公共方法
  /group/join:
    get:
      consumes:
        - multipart/form-data
      description: room_id token 为必填
      parameters:
        - description: 群号
          in: query
          name: room_id
          required: true
          type: string
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code": 200, "msg": "加入群聊成功！"}'
          schema:
            type: string
      summary: 加入群聊接口
      tags:
        - 公共方法
  /user/delete:
    get:
      consumes:
        - application/json
      description: token 账号为必填
      parameters:
        - description: 账号
          in: query
          name: account
          required: true
          type: string
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"删除成功！"}'
          schema:
            type: string
      summary: 删除好友接口
      tags:
        - 公共方法
  /user/file:
    post:
      consumes:
        - application/json
      description: |-
        上传文件
        file token为必填
      parameters:
        - description: 表单name
          in: formData
          name: file
          required: true
          type: file
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":1,"msg":"\u0001个文件上传成功","url":"127.0.0.1:8080/img/12.png"}'
          schema:
            type: string
      summary: 上传文件接口
      tags:
        - 公共方法
  /user/friend_list:
    get:
      consumes:
        - application/json
      description: token 为必填
      parameters:
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{ "code": 200, "data": {"data": [    {"Indently": "6a2a462c-a107-48ea-82e5-74e308327e6f",
            "Username": "admin", "Password": "21232f297a57a5a743894a0e4a801fc3", "Use_status":
            0, "Register_time": "2023-03-13 17:05:08","Email": "3096407764@qq.com",
            "account": "3169387148"}]}, "msg": "获取数据成功！"}'
          schema:
            type: string
      summary: 好友列表接口
      tags:
        - 公共方法
  /user/get_message:
    get:
      consumes:
        - application/json
      description: room_id token 为必填 pageSize默认值为1 选填
      parameters:
        - description: 房间号
          in: query
          name: room_id
          required: true
          type: string
        - description: token
          in: header
          name: token
          required: true
          type: string
        - description: pageSize
          in: query
          name: pageSize
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":1,"data":{"data":[{"id":29,"idently":"6a2a462c-a107-48ea-82e5-74e308327e6f","message_id":6858759,"message":"你好，我是张三","room_idently":"0820018","messagesend_time":1679052325},{"id":30,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":72843315,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679052347},{"id":31,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":91900639,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679054157},{"id":32,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":63367923,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679054157},{"id":33,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":30613339,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679054158}]},"msg":"获取数据成功！"}'
          schema:
            type: string
      summary: 获取聊天记录接口
      tags:
        - 公共方法
  /user/join:
    get:
      consumes:
        - application/json
      description: 账号 token 为必填
      parameters:
        - description: 账号
          in: query
          name: account
          required: true
          type: string
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"添加好友成功！"}'
          schema:
            type: string
      summary: 添加好友接口
      tags:
        - 公共方法
  /user/login:
    post:
      consumes:
        - multipart/form-data
      description: 用户名 密码 验证码为必填
      parameters:
        - description: 用户名
          in: formData
          name: username
          required: true
          type: string
        - description: 密码
          in: formData
          name: password
          required: true
          type: string
        - description: 验证码
          in: formData
          name: code
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code": 200, "msg": "登陆成功", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmRlbnRseSI6IjZhMmE0NjJjLWExMDctNDhlYS04MmU1LTc0ZTMwODMyN2U2ZiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpc3MiOiJ0ZXN0IiwiZXhwIjoxNjc4Nzg2NTM1fQ.P4dJ_f2UGhKbpiIqHxTxghRKwKIlCpF2XjryHCSnKKk"}'
          schema:
            type: string
      summary: 登录接口
      tags:
        - 公共方法
  /user/online:
    get:
      consumes:
        - application/json
      description: account 为必填
      parameters:
        - description: account
          in: query
          name: account
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{ "code": 200, "msg": "获取用户状态成功！", "status": true }'
          schema:
            type: string
      summary: 获取好友在线状态接口
      tags:
        - 公共方法
  /user/recallchatrecord:
    get:
      consumes:
        - application/json
      description: message_id token 为必填
      parameters:
        - description: 房间号
          in: query
          name: message_id
          required: true
          type: string
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":1,"data":{"data":[{"id":29,"idently":"6a2a462c-a107-48ea-82e5-74e308327e6f","message_id":6858759,"message":"你好，我是张三","room_idently":"0820018","messagesend_time":1679052325},{"id":30,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":72843315,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679052347},{"id":31,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":91900639,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679054157},{"id":32,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":63367923,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679054157},{"id":33,"idently":"cacda2d3-4a77-4afa-94b5-6ff2c036d126","message_id":30613339,"message":"你好，我是李四","room_idently":"0820018","messagesend_time":1679054158}]},"msg":"获取数据成功！"}'
          schema:
            type: string
      summary: 消息撤回接口
      tags:
        - 公共方法
  /user/register:
    post:
      consumes:
        - multipart/form-data
      description: 用户名 密码 邮箱为必填
      parameters:
        - description: 用户名
          in: formData
          name: username
          required: true
          type: string
        - description: 密码
          in: formData
          name: password
          required: true
          type: string
        - description: 邮箱
          in: formData
          name: email
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"account": "3169387148", "code": 200, "msg": "注册成功"}'
          schema:
            type: ""
      summary: 注册接口
      tags:
        - 公共方法
  /user/send_code:
    get:
      consumes:
        - application/json
      description: 用户名 为必填
      parameters:
        - description: 用户名
          in: query
          name: username
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{ "code": "530757", "msg": "获取验证码成功！" }'
          schema:
            type: string
      summary: 验证码接口
      tags:
        - 公共方法
  /user/setheadpicture:
    post:
      consumes:
        - multipart/form-data
      description: file token为必填
      parameters:
        - description: 表单name
          in: formData
          name: HeadPicture
          required: true
          type: file
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"account": "3169387148", "code": 200, "msg": "注册成功"}'
          schema:
            type: ""
      summary: 上传头像接口
      tags:
        - 公共方法
  /user/userinfo:
    get:
      consumes:
        - multipart/form-data
      description: token 为必填
      parameters:
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"data":{"Indently":"949c770f-0b1e-4ca0-a15a-927ee5396c3b","Username":"aadmin","Password":"21232f297a57a5a743894a0e4a801fc3","Use_status":0,"Register_time":"2023-03-12
            19:07:30","Email":"3096407769@qq.com","account":"8356511203"}},"msg":"获取数据成功！"}'
          schema:
            type: string
      summary: 获取用户信息接口
      tags:
        - 公共方法
  /user/websocket:
    get:
      consumes:
        - application/json
      description: token 为必填
      parameters:
        - description: token
          in: header
          name: token
          required: true
          type: string
      produces:
        - application/json
      responses: { }
      summary: websocket连接接口
      tags:
        - 公共方法
swagger: "2.0"
